// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

type PrismaConfig = {
  schema: string;
  migrations: {
    path: string;
    seed: string;
  };
  datasource: {
    url: string;
  };
};

function defineConfig(config: PrismaConfig): PrismaConfig {
  return config;
}

function env(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Environment variable ${name} is not set`);
  }
  return value;
}
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'node prisma/seed.mts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
